version: '3'

services:
  db:
    image: postgres:15-alpine
    container_name: zahaam-postgres
    restart: always
    environment:
      - POSTGRES_USER=zahaam
      - POSTGRES_PASSWORD=zahaampassword
      - POSTGRES_DB=stock_prediction
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: zahaam-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://zahaam:zahaampassword@db:5432/stock_prediction
    depends_on:
      - db
    volumes:
      - ./stock-prediction/backend:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: zahaam-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./stock-prediction/frontend:/app

volumes:
  postgres_data:
