version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: zahaam-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./stock-prediction/backend/stock_prediction.db:/app/stock_prediction.db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: zahaam-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
